version: '2'
services:
    flowerapp-app:
        image: flowerapp
        external_links:
            - flowerapp-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/flowerApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flowerapp-postgresql:
        extends:
            file: postgresql.yml
            service: flowerapp-postgresql
